version: "3"

services:
    mongodb:
        image: mongo:6.0.4
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: passwort
            MONGO_INITDB_DATABASE: banki
        ports:
            - 27017:27017
    node:
        image: deniskasak/banki:latest
        container_name: node
        restart: always
        ports:
            - 80:80
        depends_on:
            - mongodb
        stdin_open: true
        tty: true
        environment:
            - MONGODB_IN_CONTAINER=1