name: Docker Image CI

on:
  push:
    branches: [ "productive" ]
  pull_request:
    branches: [ "productive" ]

jobs:

  RunOnUbuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Docker image 
      run: docker build . --file Dockerfile --tag deniskasak/banki:ubuntu
    - name: Push image
      run: docker push ${{secrets.DOCKER_USER}}/banki:ubuntu

  RunOnMacOs:

      runs-on: macos-latest

      steps:
      - shell: bash
      - uses: actions/checkout@v3
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Docker image 
        run: docker build . --file Dockerfile --tag deniskasak/banki:macos
      - name: Push image
        run: docker push ${{secrets.DOCKER_USER}}/banki:macos
  
  RunOnWindows:

    runs-on: windows-latest

    steps:
    - shell: bash
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Docker image 
      run: docker build . --file Dockerfile --tag deniskasak/banki:windows
    - name: Push image
      run: docker push ${{secrets.DOCKER_USER}}/banki:windows
