name: Docker Image CI

on:
  push:
    branches: ["productive"]
  pull_request:
    branches: ["productive"]

jobs:
  RunOnUbuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
          ecr: auto
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag deniskasak/banki:ubuntu
      - name: Push image
        run: docker push ${{secrets.DOCKER_USER}}/banki:ubuntu

  RunOnMacOs:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
          ecr: auto
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag deniskasak/banki:macos
      - name: Push image
        run: docker push ${{secrets.DOCKER_USER}}/banki:macos

  RunOnWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
          ecr: auto
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag deniskasak/banki:windows
      - name: Push image
        run: docker push ${{secrets.DOCKER_USER}}/banki:windows
